[build-system]
requires = ["setuptools>=83.0.0"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "google"
known_thirdparty = ["concordia"]

[tool.pip-tools]
allow_unsafe = true
generate_hashes = true
reuse_hashes = true
strip_extras = true

[tool.pyink]
line-length = 80
unstable = true
pyink-indentation = 2
pyink-use-majority-quotes = true
pyink-annotation-pragmas = [
  "noqa",
  "pylint:",
  "type: ignore",
  "pytype:",
  "pyrefly:",
  "mypy:",
  "pyright:",
  "pyre-",
]

[tool.pytest.ini_options]
required_plugins = ["pytest-xdist"]
addopts = "-n auto"
testpaths = ["concordia", "examples"]

[tool.pyrefly]
# See //third_party/pyrefly/pyrefly.toml
infer-with-first-use = false
check-unannotated-defs = true
infer-return-types = "never"

[tool.pyrefly.errors]
abstract-method-call = false
bad-dunder-all = false
bad-override-mutable-attribute = false
bad-override-param-name = false
implicit-import = false
protocol-implicitly-defined-attribute = false
redefinition = false
redundant-condition = false
unreachable = false
unsafe-overlap = false
unused-coroutine = false
