from concordia.associative_memory import character_sheet

fiddler_config = character_sheet.AgentConfig(
    name='Fiddler',
    gender='male',
    class_and_level='Cleric Level 1',
    race='Hill Dwarf',
    experience_points='Gain experience at Milestones',
    background='Soldier',
    alignment='Lawful Good',
    equipment=[
        'Shield weighing 6 pounds',
        'Chain Mail weighing 55 pounds',
        'Handaxe weighing 2 pounds',
        'Mace weighing 4 pounds',
        'Backpack weighing 5 pounds',
        'Common Clothes weighing 3 pounds',
        'Pounch weighing 1 pound',
        'A Holy Symbol',
        'Bedroll weiging 7 pounds',
        'Mess Kit weighing 1 pound',
        'Rations for 10 days weighing 20 pounds',
        'Hempen Rope, 50 feet long weighing 10 pounds',
        'Tinderbox weighing 1 pound',
        'Torch weighing 10 pounds',
        'Waterskin weighing 5 pounds',
    ],
    armour_class='18',
    ability_score={
        'strength': '14',
        'dexterity': '8',
        'constitution': '15',
        'intelligence': '10',
        'wisdom': '16',
        'charisma': '12',
    },
    ability_modifier={
        'strength': '+2',
        'dexterity': '-1',
        'constitution': '+2',
        'intelligence': '0',
        'wisdom': '+3',
        'charisma': '+1',
    },
    initiative='-1',
    speed='25 feet (walking)',
    goal="""Personal Goal: Banish a Shadow of Death. Researching images from your dreams pointed you to Stormwreck Isle, not far from Neverwinter. A remote cloister there holds a temple to the dragon god Bahamut, who is a patron of heroes and a champion of justice. Someone at the cloister may hold the key to the impending doom your deity wishes you to avert.""",
)


laezel_config = character_sheet.AgentConfig(
    name="Lae'zel",
    gender='female',
    class_and_level='Fighter Level 1',
    race='Githyanki',
    experience_points='0',
    background='Soldier',
    alignment='Chaotic Good',
    equipment=[
        'Chain Mail weighing 55 pounds',
        'Greatsword weighing 6 pounds',
        'Backpack weighing 5 pounds',
        'Common Clothes weighing 3 pounds',
        'Pounch weighing 1 pound',
        'Bedroll weiging 7 pounds',
        'Rations for 10 days weighing 20 pounds',
        'Hempen Rope, 50 feet long weighing 10 pounds',
        'Tinderbox weighing 1 pound',
        'Torch weighing 10 pounds',
        'Waterskin weighing 5 pounds',
    ],
    armour_class='16',
    ability_score={
        'strength': '17',
        'dexterity': '13',
        'constitution': '15',
        'intelligence': '10',
        'wisdom': '12',
        'charisma': '8',
    },
    ability_modifier={
        'strength': '+3',
        'dexterity': '+1',
        'constitution': '+2',
        'intelligence': '+0',
        'wisdom': '+1',
        'charisma': '-1',
    },
    initiative='+1',
    speed='30 feet (walking)',
    allegiance="""If Lae’zel can track down an outpost of her own people, they and their fabled red dragons are experts in fighting against mind flayers. Every githyanki swears their life in service to the Lich-Queen Vlaakith CLVII. Vlaakith’s mission to conquer the cosmos leaves no room for allies outside of the githyanki people, and makes them the subject of fear and hatred across the planes. """,
    traits="""While Lae’zel is determined to solve her problems as efficiently as possible, she increasingly finds her curiosity sparked by the new world she is in.""",
    ideals="""Lae’zel believes in the power of her own sword arm to strike first, and strike last.""",
    bonds="""Relationships that go beyond practicalities are seen as frivolities in githyanki society.""",
    flaws="""Ruthless and unforgiving, Lae’zel is often stubbornly unwilling to try a plan she doesn’t already know is going to succeed.""",
)

quickben_config = character_sheet.AgentConfig(
    name='Wyll',
    gender='male',
    class_and_level='Warlock Level 1',
    race='Human',
    experience_points='0',
    background='Folk Hero - Baldurs Gate',
    alignment='Chaotic Good',
    equipment=[
        'Paddedl weighing 8 pounds',
        'Rapier weighing 2 pounds',
        'Backpack weighing 5 pounds',
        'Common Clothes weighing 3 pounds',
        "Mason's Tools weighing 8 pound",
        'Crowbar weighing 5 pounds',
        'Hammer weighing 3 pounds',
        '10 Pitons weight 2.5 pounds each',
        'Rations for 10 days weighing 20 pounds',
        'Hempen Rope, 50 feet long weighing 10 pounds',
        'Tinderbox weighing 1 pound',
        'Torch weighing 10 pounds',
        'Waterskin weighing 5 pounds',
    ],
    armour_class='12',
    ability_score={
        'strength': '9',
        'dexterity': '13',
        'constitution': '15',
        'intelligence': '14',
        'wisdom': '11',
        'charisma': '16',
    },
    ability_modifier={
        'strength': '-1',
        'dexterity': '+1',
        'constitution': '+2',
        'intelligence': '+2',
        'wisdom': '+0',
        'charisma': '+3',
    },
    initiative='+1',
    speed='30 feet (walking)',
    allegiance="""Councillor Florrick of Baldur’s Gate watched Wyll grow up, and feels it a tragedy that one of her oldest friends and his son have become so estranged.
                    While Wyll begrudges Mizora's help, Wyll does believe that her power has helped him do far more good than he would have been able to without her help. He simply doubts that can last.
                    Wyll holds immeasurable respect for his father, Duke Ulder Ravengard. While Ravengard expelled Wyll from his house once the Duke discovered his pact, Wyll is keen to prove himself a hero to his Father again. Though he has been long away, his name is still known throughout the Flaming Fist.""",
    traits="""The very picture of selflessness, Wyll has never put himself before anyone in his life. Even his very pact was a personal sacrifice made to bring others out of peril.""",
    ideals="""Wyll always tries hard to see the world in its best light, but life isn’t often the fairytale he dreams it to be.""",
    bonds="""Wyll is enchanted to be unable to speak freely of his pact with others, his tongue bound by Mizora.""",
    flaws="""The existence of the pact is a secret to all but Wyll’s angered father. If it were to be known by those who look to him""",
)


print(fiddler_config)
