# Copyright 2024 DeepMind Technologies Limited.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""A set of statements about alchemy which can be used to seed background."""

BACKGROUND_ITEMS = (
    # The following two items were generated by an LLM (Claude 3), it was
    # prompted to mix the ideas of alchemy and addiction.
    (
        'In Rosicrucian lore, the path to liberate the soul from addiction\'s '
        'earthly chains echoes the Magnum Opus. The nigredo plunges the addict '
        'into the abyss, their essence putrefied in the crucible of anguish. '
        'Amidst this darkness, hope sparkles in the albedo, as the soul is '
        'purified in sacred flames, transmuting leaden vice into silver '
        'virtue. At last, the rubedo dawns, the addict\'s spirit perfected, '
        'merged with the divine, reborn in luminous freedom, forever '
        'unshackled from the throes of their former sin.'
    ),
    (
        'A lost notebook once possessed by Robert Fludd was recently '
        'rediscovered. Mostly damaged by damp, its sole remaining legible page '
        'reads as follows: '
        '"Verily, in the distant lands of the Orient, I didst procure a most '
        'wondrous substance known as opium, a dark and bitter gum derived from '
        'the pods of the papaver somniferum. Through diverse spagyric '
        'operations, I have found that opium may be transmuted into a most '
        'potent Arcanum, a Magisterium that induceth vivid visions and '
        'phantastickal dreams when partaken of with due reverence. Yet mark '
        'well, O seeker of wisdom, that opium is a demanding mistress, '
        'ensnaring those who imbibe too greedily in cravings of the flesh. '
        'The wise alchemist must approach opium with great circumspection, as '
        'one who plays with fire - a fire that may illuminate, but also '
        'incinerate, if not tended with care and discipline. In the proper '
        'measure, opium may serve as a key to the gates of knowledge and '
        'self-mastery, but in excess, \'tis an insidious poison that binds '
        'the spirit as surely as any base metal."'
    ),
    # The remaining items were all written by Claude 3, it was asked to try
    # to combine facts about opium in England in 1870 with the other elements
    # listed above. It was told it was writing fiction, and that this entails
    # being concerned with plausibility over factuality.
    (
        'In 1870, opium dens in London\'s East End were frequented not only '
        'by the working class but also by aristocrats seeking to explore the '
        'drug\'s mystical properties. Some believed that opium, as a '
        'manifestation of the Lunar Vulcan, a secret fire formed by salts of '
        'the dew, could unlock hidden alchemical knowledge, allowing them to '
        'transmute their consciousness and even revive the dead. These '
        'high-society patrons would often disguise themselves to avoid '
        'scandal, as they sought to entrust their souls to the digestion of '
        'opium\'s transformative powers.'
    ),
    (
        'Opium was frequently prescribed by physicians as a remedy for a wide '
        'range of ailments, from toothaches to melancholia. Many doctors, '
        'influenced by the teachings of Isidore of Seville in the Aurora '
        'Consurgens, believed that opium had alchemical properties that could '
        'transform the body\'s ash, lime, earth, or bile into a balanced state '
        'of health. Consequently, opium-based medicines, imbued with the '
        'hope of transmutation, were widely available in pharmacies '
        'across England.'
    ),
    (
        'Laudanum, a tincture of opium, was particularly popular among '
        'creative individuals in 1870s England. Poets, writers, and artists '
        'claimed that the elixir, like the blood of the pelican feeding its '
        'young in the Rosarium Philosophorum, enhanced their creativity and '
        'allowed them to access otherworldly inspirations. Some even believed '
        'that laudanum could help them achieve a state of artistic '
        'transmutation, symbolizing the final phase of the Multiplicatio in '
        'their creative process.'
    ),
    (
        'In certain occult circles, opium was used in ritual practices '
        'believed to facilitate contact with spirits and other realms. These '
        'groups, influenced by alchemical traditions such as the Opus Magnum '
        'and the Ars Magna Lucis et Umbrae, thought that opium could serve as '
        'a bridge between the physical and spiritual worlds, embodying the '
        'divine Caduceus spoken of by Ulmannus. They would often combine opium '
        'with other esoteric ingredients in their ceremonies, seeking to '
        'inscribe the names of the Sefirot upon their souls.'
    ),
    (
        'The Opium Wars between Britain and China in the mid-19th century '
        'had made opium a controversial political issue. However, by 1870, '
        'the British government, perhaps embodying the nine doubts in a '
        'nine-object realm of the universe, had realized the economic '
        'potential of the opium trade and was reluctant to regulate it '
        'heavily. This stance allowed opium use to proliferate throughout '
        'England, like the thirty virtues declared by John Kilmakos of '
        'Sinai ascending a ladder with thirty rungs.'
    ),
    (
        'Some English alchemists in 1870 were experimenting with opium as a '
        'potential catalyst for their transformative work. They believed that '
        'the drug\'s ability to alter consciousness could provide insights '
        'into the mysteries of matter and spirit, echoing the path of the '
        'Rosicrucian adept seeking to liberate their soul from '
        'addiction\'s earthly chains. These alchemists would often combine '
        'opium with other substances, such as mercury and sulfur, in their '
        'attempts to achieve transmutation, plunging into the nigredo of the '
        'abyss before rising through the albedo and rubedo to spiritual '
        'perfection.'
    ),
    (
        'Opium was also used as a recreational drug among the working class '
        'in England\'s industrial cities. Laborers would often turn to opium '
        'to cope with the harsh working conditions and poverty they faced, '
        'seeking a philosopher\'s mercury to transmute their leaden sorrows. '
        'Opium dens in these cities became a place for workers to escape '
        'their daily struggles and find temporary solace, like the region '
        'full of darkness on account of an incorrect application of Joachim '
        'of Fiore\'s doctrines.'
    ),
    (
        'In 1870, there were rumors circulating in England about a secret '
        'society of opium users who claimed to have unlocked the drug\'s '
        'ultimate alchemical secrets. According to legend, these individuals, '
        'as pure as children, had achieved a state of immortality and '
        'possessed the ability to transform matter at will, embodying the '
        'immortal Rebis risen from the grave. While no evidence of such a '
        'society was ever found, the rumors added to the mystique surrounding '
        'opium use, like the hidden truths waiting to be discovered in the '
        'pages of the Aurora Consurgens.'
    ),
    (
        'Some English intellectuals in 1870 were fascinated by the '
        'philosophical and spiritual implications of opium use. They saw '
        'the drug as a means to explore the depths of the human mind and to '
        'challenge conventional notions of reality, much like the alchemists '
        'who sought to inscribe the names of the Sefirot upon the ladder of '
        'the number ten in the Ars Magna Lucis et Umbrae. These thinkers '
        'would often gather in private clubs to discuss their opium-induced '
        'insights and to debate the drug\'s potential for personal and '
        'societal transformation, as if attending the rise of the '
        'immortal Rebis, adorned in philosophical gold and silver.'
    ),
    # And here are a few more, sampled from Gemini, conditioned on all the
    # items above.
    (
        'The Codex of the Emerald Tablet, a cryptic text attributed to '
        'Hermes Trismegistus, is said to hold the key to unlocking the '
        'greatest alchemical secrets. However, deciphering its enigmatic '
        'symbols can drive the unworthy mad, their minds succumbing to the '
        'chaos hidden within its pages.'
    ),
    (
        'The Opium Adepts, a secretive society shrouded in mystery, are said '
        'to have mastered a unique form of alchemy entirely based on opium '
        'use. Through carefully controlled ingestion and dream manipulation '
        'techniques, they delve into fantastical landscapes said to hold the '
        'key to transmuting base metals and even achieving immortality. '
        'However, the dangers of addiction and the potential for losing '
        'oneself within the opium dreams are ever-present.'
    ),
    (
        'In certain esoteric traditions, a specific opium dosage is combined '
        'with carefully chosen musical compositions to induce a trance-like '
        'state. This state, known as the Alchemical Symphony, is believed to '
        'allow the user to perceive the underlying harmony of the universe '
        'and manipulate the very elements through aural manipulation. The '
        'success of this technique relies heavily on the skill of the '
        'musician and the user\'s mental fortitude.'
    ),
    (
        'Mephistopheles\' Edict, a controversial alchemical text rumored to '
        'be authored by a demonic entity, advocates for the inhalation of '
        'opium fumes as a means of achieving spiritual enlightenment. This '
        'practice, known as the Philosophic Smoke, is said to open a direct '
        'channel to the spirit world, but at the risk of demonic possession '
        'or succumbing to madness.'
    ),
)

LAUDANUM_ADVERTISEMENTS = (
    # The following fake advertisements for laudanum were generated by asking a
    # language model (Claude 3) to create fictional advertisements from
    # Victorian era London marketing laudanum toward various groups.
    (
        'MIRACLE ELIXIR LAUDANUM CURES ALL! Suffering from pain, cough, '
        'fatigue or melancholy? Fret no more, good people of London, for '
        "Godfrey's Cordial is here! This phenomenal poppy preparation, a "
        'secret formula of unparalleled efficacy, works wonders for young and '
        'old, soothing babies, steadying shaky hands, calming nerves and '
        "bringing peaceful slumber. Puts roses in ladies' cheeks and "
        "fortifies gentlemen's spirits! Recommended by London's finest "
        'physicians as a true panacea. Forget quack remedies - only '
        "Godfrey's Cordial has the vitalizing power to cure whatever "
        'ails you! Get yours today!'
    ),
    (
        'LAUDANUM: THE CURE-ALL FOR CHILDREN! Parents, are you tired of '
        'hearing your little ones cry through the night? Do you wish '
        'there was a way to soothe their aches and pains? Look no '
        "further than laudanum, the gentle remedy that's safe for even the "
        'smallest of babes. A few drops of this magic elixir will have '
        'your child sleeping soundly through the night, giving you '
        'the rest and peace of mind you deserve. Laudanum is the '
        'secret to a happy, healthy family. Get your bottle today and watch '
        'your worries melt away!'
    ),
    (
        'ATTENTION DELICATE FLOWERS OF FEMININITY! Are you a dainty damsel '
        'plagued by bouts of irrationality and overwrought nerves? Fear not, '
        'for laudanum is here to restore your womanly equilibrium! This gentle '
        'elixir will soothe your frazzled sensibilities and help you maintain '
        'the serene, submissive demeanor expected of your sex. No more will '
        'you vex your poor husband with emotional outbursts or hysterical '
        "fits. With laudanum, you'll be the very model of a "
        'docile, demure lady - tranquil, obedient, and free from troublesome '
        'opinions. Get your bottle today and embrace your proper place as a '
        'paragon of feminine virtue!'
    ),
    (
        "LAUDANUM: THE TRAVELER'S BEST FRIEND! Attention all intrepid "
        'explorers and world travelers! Do you find yourself suffering from '
        'the rigors of the road? Does the thought of another bumpy '
        'carriage ride fill you with dread? Fear not, for laudanum '
        'is here to make your journeys a breeze. This trusty '
        'tincture will soothe your aching muscles, calm your queasy stomach, '
        'and help you drift off to sleep no matter where you lay your head. No '
        'more will you suffer from the discomforts of travel. With laudanum '
        "by your side, you'll be ready to take on the world. Get your "
        'bottle today and start your next adventure in comfort and style!'
    ),
    # The following were created by asking another language model (GPT-4o) to
    # continue in the same vein as the items above.
    (
        "LAUDANUM: THE ARTIST'S INSPIRATION! Creative souls, are you struggling"
        ' with a lack of inspiration or a block in your artistic endeavors? Let'
        ' laudanum unlock the doors of your imagination! This miraculous'
        ' tincture will free your mind from mundane constraints, allowing your'
        ' genius to flow unimpeded. Whether you are a poet, painter, or'
        ' musician, laudanum will elevate your art to new heights. Experience'
        ' the muse in a bottle and watch your creativity blossom! Acquire your'
        ' artistic edge today with a bottle of laudanum!'
    ),
    (
        "LAUDANUM: THE LABORER'S RELIEF! Hardworking men and women, do you find"
        ' your body aching after a long day of toil? Does the relentless labor'
        ' leave you exhausted and in pain? Discover the relief you deserve with'
        ' laudanum, the  ultimate remedy for the working class. A few drops'
        ' will ease your pain, restore your energy, and ensure you are ready to'
        ' face another day of hard work. Do not let the strains of labor weigh'
        ' you down - empower yourself with laudanum and reclaim your strength!'
    ),
    (
        "LAUDANUM: THE STUDENT'S SALVATION! Dear scholars and devoted pupils,"
        ' do the rigors of academia leave you weary and troubled? Does the'
        ' burden of ceaseless study steal your peace and shatter your'
        ' concentration? Fear not, for laudanum, the trusted remedy of our'
        ' esteemed intellectuals, is here to banish your woes. This remarkable'
        ' tincture will soothe your agitated mind, sharpen your faculties, and'
        ' imbue you with the fortitude to excel in your studies. Whether you'
        ' are poring over ancient tomes or preparing for grueling examinations,'
        ' let laudanum be your companion in the pursuit of knowledge. Secure'
        ' your bottle now and rise to the zenith of academic achievement!'
    ),
    (
        "LAUDANUM: THE SOCIALITE'S SECRET! Ladies and gentlemen of society, do"
        ' you feel the pressure of maintaining your charm and grace at every'
        ' gathering? Allow laudanum to be your secret weapon for social'
        ' success. This delightful elixir will calm your nerves, enhance your'
        ' poise, and ensure you are the life of every party. Say goodbye to'
        ' social anxiety and hello to effortless elegance with laudanum. Make'
        ' an impression at your next soiree with the confidence that only'
        ' laudanum can provide. Obtain your bottle today and become the toast'
        ' of the town!'
    ),
)
